import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#000',
  },
  mainContent: {
    alignItems: 'center',
    paddingVertical: 20,
    backgroundColor: '#000',
    marginTop: -100
  },
  header: {
    position: 'absolute',
    top: 30,
    width: '90%',
    flexDirection: 'column',
    justifyContent: 'space-between',
    alignItems: 'center',
    zIndex: 1,
  },
  headerLeft: {
    flexDirection: 'row',
    gap: 30,
    marginTop: 25
  },
  headerRight: {
    flexDirection: 'row',
  },
  headerIcon: {
    marginLeft: 40,
  },
  badge: {
    position: 'absolute',
    right: -6,
    top: -3,
    backgroundColor: '#ff3b30',
    borderRadius: 8,
    width: 16,
    height: 16,
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'visible'
  },
  badgeText: {
    color: '#fff',
    fontSize: 10,
    fontWeight: 'bold',
  },
  profilePictureContainer: {
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 125,
    marginBottom: 50,
    left: 20
  },
  profilePicture: {
    width: 150,
    height: 150,
    borderRadius: 75,
    borderColor: '#6a0dad',
    borderWidth: 3,
  },
  editIcon: {
    width: 30,
    height: 30,    
    bottom: 40,
    left: 55,
    backgroundColor: '#6a0dad',
    borderRadius: 15,
    padding: 8,
  },
  username: {
    fontSize: 24,
    color: '#fff',
    fontWeight: '700',
    left: 20,
    marginTop: 25,
    textAlign: 'center',
    maxWidth: 200,
    overflow: 'scroll'
  },
  friendsContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#6a0dad',
    paddingVertical: 7,
    paddingHorizontal: 20,
    borderRadius: 25,
    marginBottom: 20,
  },
  friendsText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
    marginLeft: 10,
  },
  recentActivityContainer: {
    width: '90%',
    backgroundColor: '#1a1a1a',
    borderRadius: 20,
    padding: 15,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
    marginTop: 325,
    marginBottom: 20,
  },
  recentActivityTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#6a0dad',
    marginBottom: 10,
  },
  activityItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 15,
  },
  activityTextContainer: {
    marginLeft: 15,
  },
  friendsWorkoutsContainer: {
    width: '90%',
    backgroundColor: '#1a1a1a',
    borderRadius: 20,
    padding: 15,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
    marginTop: 25,
    marginBottom: 20,
  },
  friendsWorkoutsTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#6a0dad',
    marginBottom: 10,
  },
  modalBackground: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContainer: {
    width: '90%',
    height: '80%',
    backgroundColor: '#1a1a1a',
    borderRadius: 20,
    padding: 20,
    elevation: 10,
  },
  modalHeader: {
    marginBottom: 10,
  },
  modalTitle: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#6a0dad',
    textAlign: 'center',
  },
  closeButton: {
    marginTop: 10,
    backgroundColor: '#6a0dad',
    paddingVertical: 10,
    borderRadius: 10,
    alignItems: 'center',
  },
  closeButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
  tabContainer: {
    flex: 1,
    paddingTop: 10,
  },
  searchBarContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#1a1a1a',
    borderRadius: 25,
    borderColor: '#6a0dad',
    borderWidth: 1,
    paddingHorizontal: 15,
    paddingVertical: 8,
    width: '100%',
    marginBottom: 10,
  },
  searchIcon: {
    marginRight: 10,
  },
  searchBar: {
    flex: 1,
    color: '#fff',
  },
  friendItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#333',
    borderRadius: 15,
    padding: 10,
    marginVertical: 5,
  },
  friendImage: {
    width: 50,
    height: 50,
    borderRadius: 25,
    marginRight: 15,
  },
  friendName: {
    flex: 1,
    color: '#fff',
    fontSize: 16,
  },
  removeButton: {
    backgroundColor: '#ff4d4d',
    paddingVertical: 5,
    paddingHorizontal: 10,
    borderRadius: 15,
  },
  pendingButton: {
    backgroundColor: '#999',
    paddingVertical: 5,
    paddingHorizontal: 10,
    borderRadius: 15,
  },
  addButton: {
    backgroundColor: '#4CAF50',
    paddingVertical: 5,
    paddingHorizontal: 10,
    borderRadius: 15,
  },
  acceptButton: {
    backgroundColor: '#4CAF50',
    paddingVertical: 5,
    paddingHorizontal: 10,
    borderRadius: 15,
    marginRight: 5,
  },
  rejectButton: {
    backgroundColor: '#F44336',
    paddingVertical: 5,
    paddingHorizontal: 10,
    borderRadius: 15,
  },
  pendingContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  buttonText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '600',
  },
  searchResultItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#333',
    borderRadius: 15,
    padding: 10,
    marginVertical: 5,
  },
  searchResultImage: {
    width: 50,
    height: 50,
    borderRadius: 25,
    marginRight: 15,
  },
  searchResultName: {
    flex: 1,
    color: '#fff',
    fontSize: 16,
  },
  noUsersText: {
    color: '#ccc',
    fontSize: 16,
    textAlign: 'center',
    paddingVertical: 10,
  },
  modalSearchBarContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#1a1a1a',
    borderRadius: 25,
    paddingHorizontal: 15,
    paddingVertical: 8,
    width: '100%',
    marginBottom: 10,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  notificationsButton: {
    position: 'absolute',
    top: 40,
    right: 20,
    zIndex: 10,
  },
  notificationBadge: {
    position: 'absolute',
    top: -5,
    right: -5,
    backgroundColor: '#ff3b30',
    width: 18,
    height: 18,
    borderRadius: 9,
    justifyContent: 'center',
    alignItems: 'center',
  },
  badgeText: {
    color: '#fff',
    fontSize: 10,
    fontWeight: 'bold',
  },
  notificationsModalContainer: {
    width: '90%',
    backgroundColor: '#222',
    borderRadius: 20,
    padding: 20,
    maxHeight: '80%',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  notificationItem: {
    paddingVertical: 10,
    paddingHorizontal: 5,
    borderBottomColor: '#e0e0e0',
    borderBottomWidth: 1,
  },
  readNotification: {
    backgroundColor: '#3f3f3f3',
  },
  unreadNotification: {
    backgroundColor: '#777',
  },
  notificationText: {
    fontSize: 16,
    color: '#ccc',
  },
  notificationTimestamp: {
    fontSize: 12,
    color: '#ccc',
    marginTop: 2,
  },
  noNotificationsText: {
    textAlign: 'center',
    color: '#ddd',
    fontSize: 16,
    marginTop: 20,
  },
  closeButton: {
    marginTop: 20,
    backgroundColor: '#6a0dad',
    paddingVertical: 10,
    borderRadius: 25,
    alignItems: 'center',
  },
  closeButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
  notificationsTabsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginVertical: 15,
    borderBottomColor: '#6a0dad',
  },
  notificationTab: {
    paddingVertical: 10,
    paddingHorizontal: 20,
  },
  activeNotificationTab: {
    borderBottomWidth: 3,
    borderBottomColor: '#6a0dad',
  },
  notificationTabText: {
    fontSize: 16,
    color: '#aaa',
  },
  activeNotificationTabText: {
    color: '#6a0dad',
    fontWeight: 'bold',
  },
});

export default styles;
